/*
 * PersonMonitorPanel.java
 *
 * Created on July 30, 2009, 11:15 PM
 */

package com.hansonrobotics.gui.person;

import java.util.logging.Logger;

/**
 *
 * @author  Stu Baurmann
 */
public class PersonMonitorPanel extends javax.swing.JPanel {
	private static Logger	theLogger = Logger.getLogger(PersonMonitorPanel.class.getName());

	private PersonMonitorImpl		myImpl;

    /** Creates new form PersonMonitorPanel */
    public PersonMonitorPanel() {
        initComponents();
		if (!java.beans.Beans.isDesignTime()) {
			myImpl = new PersonMonitorImpl(this, personTable, obsTable);
		}
    }
	public void setObsLogInfo(String type, String id, String count) {
		lab_obsLogType.setText(type);
		lab_obsLogID.setText(id);
		lab_obsCountVal.setText(count);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queryToolsPanel = new javax.swing.JPanel();
        but_refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        personScrollPane = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        obsLogPanel = new javax.swing.JPanel();
        obsLogInfoPanel = new javax.swing.JPanel();
        lab_obsLogType = new javax.swing.JLabel();
        lab_obsLogID = new javax.swing.JLabel();
        lab_oc = new javax.swing.JLabel();
        lab_obsCountVal = new javax.swing.JLabel();
        obsScrollPane = new javax.swing.JScrollPane();
        obsTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        but_refresh.setText("refresh");
        but_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_refreshActionPerformed(evt);
            }
        });

        jLabel1.setText("PersonCues (only!) are shown in top table.  Click \"last rec obs\" to view freckle log, \"last hyp obs\" for hypo log.  ");

        javax.swing.GroupLayout queryToolsPanelLayout = new javax.swing.GroupLayout(queryToolsPanel);
        queryToolsPanel.setLayout(queryToolsPanelLayout);
        queryToolsPanelLayout.setHorizontalGroup(
            queryToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryToolsPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(but_refresh)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        queryToolsPanelLayout.setVerticalGroup(
            queryToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryToolsPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(queryToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_refresh)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(queryToolsPanel, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(110);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        personTable.setRowHeight(40);
        personScrollPane.setViewportView(personTable);

        jSplitPane1.setTopComponent(personScrollPane);

        obsLogPanel.setLayout(new java.awt.BorderLayout());

        lab_obsLogType.setText("type");

        lab_obsLogID.setText("ident");

        lab_oc.setText("Observation Count:");

        lab_obsCountVal.setText("none");

        javax.swing.GroupLayout obsLogInfoPanelLayout = new javax.swing.GroupLayout(obsLogInfoPanel);
        obsLogInfoPanel.setLayout(obsLogInfoPanelLayout);
        obsLogInfoPanelLayout.setHorizontalGroup(
            obsLogInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obsLogInfoPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lab_obsLogType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_obsLogID, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_oc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_obsCountVal)
                .addGap(266, 266, 266))
        );
        obsLogInfoPanelLayout.setVerticalGroup(
            obsLogInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obsLogInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(obsLogInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_obsLogType)
                    .addComponent(lab_obsCountVal)
                    .addComponent(lab_oc)
                    .addComponent(lab_obsLogID))
                .addGap(11, 11, 11))
        );

        obsLogPanel.add(obsLogInfoPanel, java.awt.BorderLayout.NORTH);

        obsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        obsTable.setRowHeight(40);
        obsScrollPane.setViewportView(obsTable);

        obsLogPanel.add(obsScrollPane, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(obsLogPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void but_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_refreshActionPerformed
// TODO add your handling code here:
	myImpl.updateTables();
}//GEN-LAST:event_but_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lab_obsCountVal;
    private javax.swing.JLabel lab_obsLogID;
    private javax.swing.JLabel lab_obsLogType;
    private javax.swing.JLabel lab_oc;
    private javax.swing.JPanel obsLogInfoPanel;
    private javax.swing.JPanel obsLogPanel;
    private javax.swing.JScrollPane obsScrollPane;
    private javax.swing.JTable obsTable;
    private javax.swing.JScrollPane personScrollPane;
    private javax.swing.JTable personTable;
    private javax.swing.JPanel queryToolsPanel;
    // End of variables declaration//GEN-END:variables

}
