/**
 * Copyright 2008 Hanson Robotics Inc.
 * All Rights Reserved.
 */

package org.friendularity.gui.vision;

import org.friendularity.app.freckle.FreckleFace;
import org.friendularity.gui.hypo.HypoTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author  humankind
 */
public class VisionMonitorPanel extends javax.swing.JPanel {
	private static Logger	theLogger = Logger.getLogger(VisionMonitorPanel.class.getName());

	VisionMonitorChannelImpl myVMCI;
    /** Creates new form VisionMonitorPanel */
    public VisionMonitorPanel() {
        initComponents();
        if (!java.beans.Beans.isDesignTime()) {
			VisionMonitorChannelImpl vmci = new VisionMonitorChannelImpl();
			myVMCI = vmci;
			VisionMonitorChannelBean configBean = myChannelControlsPanel.getChannelConfigBean();
			vmci.setConfigBean(configBean);
			vmci.setDrawingPanel(myVisionSwingPanel);
			HypoTableModel htm = new HypoTableModel(vmci.getFaceModel());
			hypoTable.setModel(htm);

			ObservableList<FreckleFace> kfList = vmci.getObservableKnownFaceList();

			BindingGroup kfbg = new BindingGroup();
			JTableBinding kftb = SwingBindings.createJTableBinding(
					AutoBinding.UpdateStrategy.READ, kfList, popTable);

			JTableBinding.ColumnBinding kfColumnBinding = kftb.addColumnBinding(
					ELProperty.create("${freckleID}"));
			kfColumnBinding.setColumnName("Freckle ID");
			kfColumnBinding.setColumnClass(String.class);
			
			kfColumnBinding = kftb.addColumnBinding(
					ELProperty.create("${personName}"));
			kfColumnBinding.setColumnName("Person Name");
			kfColumnBinding.setColumnClass(String.class);					
			
			kfColumnBinding = kftb.addColumnBinding(
					ELProperty.create("${matchedObservationCount}"));
			kfColumnBinding.setColumnName("# Matched Obs.");
			kfColumnBinding.setColumnClass(Integer.class);			
		
			kfbg.addBinding(kftb);
			kfbg.bind();

			but_updateMotionDetectParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_setMotionParams();
            }
        });
			
		}
    }
    public void doStartAll() {
		VisionMonitorChannelBean vmcb = myChannelControlsPanel.getChannelConfigBean();
		vmcb.setGrabbingFrames(true);
		vmcb.setTrackingFaces(true);
		vmcb.setDetectingMotion(true);
		vmcb.setDetectingFaces(true);
	}
	public void doStartRecognizingFaces() {
		// TODO:  If freckler is not configured, disable the button.
		VisionMonitorChannelBean vmcb = myChannelControlsPanel.getChannelConfigBean();
		try {
			vmcb.setRecognizingFaces(true);
		} catch (Throwable t) {
			theLogger.log(Level.SEVERE, "Error in face recognition startup", t);
			try {
				vmcb.setRecognizingFaces(false);
			} catch (Throwable t2) {
				theLogger.log(Level.SEVERE, "Ouch - error trying to disable face recognition", t2);
			}
		}
	}
	public void disableControls() { 
		myChannelControlsPanel.disableControls();
	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        myChannelControlsPanel = new org.friendularity.gui.vision.VisionChannelControlsPanel();
        myVisionSwingPanel = new org.friendularity.gui.vision.VisionSwingPanel();
        statsSplitPane = new javax.swing.JSplitPane();
        hypoScrollPane = new javax.swing.JScrollPane();
        hypoTable = new javax.swing.JTable();
        popScrollPane = new javax.swing.JScrollPane();
        popTable = new javax.swing.JTable();
        but_updateMotionDetectParams = new javax.swing.JButton();

        jButton1.setText("up");

        myVisionSwingPanel.setBackground(new java.awt.Color(0, 153, 51));
        myVisionSwingPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 102, 0)));
        myVisionSwingPanel.setImageSource(null);
        myVisionSwingPanel.setMaximumSize(new java.awt.Dimension(320, 240));
        myVisionSwingPanel.setMinimumSize(new java.awt.Dimension(320, 240));
        myVisionSwingPanel.setPreferredSize(new java.awt.Dimension(320, 240));

        org.jdesktop.layout.GroupLayout myVisionSwingPanelLayout = new org.jdesktop.layout.GroupLayout(myVisionSwingPanel);
        myVisionSwingPanel.setLayout(myVisionSwingPanelLayout);
        myVisionSwingPanelLayout.setHorizontalGroup(
            myVisionSwingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 310, Short.MAX_VALUE)
        );
        myVisionSwingPanelLayout.setVerticalGroup(
            myVisionSwingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 230, Short.MAX_VALUE)
        );

        statsSplitPane.setDividerLocation(140);
        statsSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        hypoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        hypoScrollPane.setViewportView(hypoTable);

        statsSplitPane.setLeftComponent(hypoScrollPane);

        popTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        popScrollPane.setViewportView(popTable);

        statsSplitPane.setRightComponent(popScrollPane);

        but_updateMotionDetectParams.setText("update motion detect params");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(myChannelControlsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(myVisionSwingPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(but_updateMotionDetectParams))
                .addContainerGap(18, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, statsSplitPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(myChannelControlsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(myVisionSwingPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(but_updateMotionDetectParams)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                .add(statsSplitPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	public void action_setMotionParams() {
		Integer histDur = myChannelControlsPanel.getHistDur();
		Integer segDurThresh = myChannelControlsPanel.getSegDurThresh();
		Integer deltaAmpThresh = myChannelControlsPanel.getDeltaAmpThresh();
		Integer resultAmpThresh = myChannelControlsPanel.getResultAmpThresh();
		myVMCI.setMotionDetectParams(histDur, segDurThresh, deltaAmpThresh, resultAmpThresh);
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_updateMotionDetectParams;
    private javax.swing.JScrollPane hypoScrollPane;
    private javax.swing.JTable hypoTable;
    private javax.swing.JButton jButton1;
    private org.friendularity.gui.vision.VisionChannelControlsPanel myChannelControlsPanel;
    private org.friendularity.gui.vision.VisionSwingPanel myVisionSwingPanel;
    private javax.swing.JScrollPane popScrollPane;
    private javax.swing.JTable popTable;
    private javax.swing.JSplitPane statsSplitPane;
    // End of variables declaration//GEN-END:variables

}
