/**
 * Copyright 2008 Hanson Robotics Inc.
 * All Rights Reserved.
 */

package org.friendularity.gui.blending;

import java.util.logging.Logger;
/**
 *
 * @author  humankind
 */
public class BlendingMonitorPanel extends javax.swing.JPanel {
	private static Logger	theLogger = Logger.getLogger(BlendingMonitorPanel.class.getName());
	
	private		BlendingMonitorImpl		myBlendingMonitorImpl;

 
    /** Creates new form BlendingMonitorPanel */
    public BlendingMonitorPanel() {
        initComponents();
		if (!java.beans.Beans.isDesignTime()) {
			BlendingMonitorImpl bmi = new BlendingMonitorImpl();
			bmi.setConfigBean(myBlendingMonitorBean);
			myBlendingMonitorImpl = bmi;
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        myBlendingMonitorBean = new org.friendularity.gui.blending.BlendingMonitorBean();
        jLabel1 = new javax.swing.JLabel();
        panel_toggles = new javax.swing.JPanel();
        toggleJoystickGazeRule = new javax.swing.JToggleButton();
        toggleAttentionRule = new javax.swing.JToggleButton();
        tog_viseme = new javax.swing.JToggleButton();
        tglAnims = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        panel_buttons = new javax.swing.JPanel();
        but_resetServos = new javax.swing.JButton();
        but_stopAllAnims = new javax.swing.JButton();

        jLabel1.setText("Enable or disable motion features using these toggle buttons:");

        toggleJoystickGazeRule.setText("joystick");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myBlendingMonitorBean, org.jdesktop.beansbinding.ELProperty.create("${usingJoystickGazeControl}"), toggleJoystickGazeRule, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        toggleAttentionRule.setText("attention");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myBlendingMonitorBean, org.jdesktop.beansbinding.ELProperty.create("${usingAnyFaceAttentionRule}"), toggleAttentionRule, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        toggleAttentionRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAttentionRuleActionPerformed(evt);
            }
        });

        tog_viseme.setText("viseme");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myBlendingMonitorBean, org.jdesktop.beansbinding.ELProperty.create("${usingVisemeRule}"), tog_viseme, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        tglAnims.setText("animation scripts");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myBlendingMonitorBean, org.jdesktop.beansbinding.ELProperty.create("${usingScriptedAnimations}"), tglAnims, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        tglAnims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglAnimsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_togglesLayout = new javax.swing.GroupLayout(panel_toggles);
        panel_toggles.setLayout(panel_togglesLayout);
        panel_togglesLayout.setHorizontalGroup(
            panel_togglesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_togglesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_togglesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toggleAttentionRule, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(tog_viseme, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(toggleJoystickGazeRule, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(tglAnims, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_togglesLayout.setVerticalGroup(
            panel_togglesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_togglesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toggleAttentionRule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tog_viseme)
                .addGap(11, 11, 11)
                .addComponent(tglAnims)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toggleJoystickGazeRule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Use these one-shot actions to quiet and recenter the robot:");

        but_resetServos.setText("Reset Servo Positions");
        but_resetServos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_resetServosActionPerformed(evt);
            }
        });

        but_stopAllAnims.setText("Stop All Animation Scripts");
        but_stopAllAnims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_stopAllAnimsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_buttonsLayout = new javax.swing.GroupLayout(panel_buttons);
        panel_buttons.setLayout(panel_buttonsLayout);
        panel_buttonsLayout.setHorizontalGroup(
            panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(but_resetServos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_stopAllAnims, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_buttonsLayout.setVerticalGroup(
            panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(but_stopAllAnims)
                .addGap(7, 7, 7)
                .addComponent(but_resetServos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_toggles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_toggles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(panel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

private void toggleAttentionRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAttentionRuleActionPerformed
	theLogger.info("Attention gaze toggled");
}//GEN-LAST:event_toggleAttentionRuleActionPerformed

private void btn_frameRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frameRateActionPerformed
	
}//GEN-LAST:event_btn_frameRateActionPerformed

private void tglAnimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglAnimsActionPerformed
	// myBlendingMonitorImpl.setAnimationCue(tglAnims.isSelected());
	theLogger.info("Animation playback toggled");
}//GEN-LAST:event_tglAnimsActionPerformed

private void but_resetServosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_resetServosActionPerformed
	theLogger.info("Resetting servos");
	myBlendingMonitorImpl.resetServos();
}//GEN-LAST:event_but_resetServosActionPerformed

private void but_stopAllAnimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_stopAllAnimsActionPerformed
	theLogger.info("Stopping animations");
	myBlendingMonitorImpl.stopAllAnimations();
}//GEN-LAST:event_but_stopAllAnimsActionPerformed
	public void doStartAll() {
		myBlendingMonitorBean.setUsingVisemeRule(true);
		myBlendingMonitorBean.setUsingScriptedAnimations(true);
		myBlendingMonitorBean.setUsingAnyFaceAttentionRule(true);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_resetServos;
    private javax.swing.JButton but_stopAllAnims;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private org.friendularity.gui.blending.BlendingMonitorBean myBlendingMonitorBean;
    private javax.swing.JPanel panel_buttons;
    private javax.swing.JPanel panel_toggles;
    private javax.swing.JToggleButton tglAnims;
    private javax.swing.JToggleButton tog_viseme;
    private javax.swing.JToggleButton toggleAttentionRule;
    private javax.swing.JToggleButton toggleJoystickGazeRule;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
