/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdvancedPanelFrame.java
 *
 * Created on Jan 6, 2010, 10:00:27 PM
 */

package org.friendularity.dictation.gui.advanced;

import org.friendularity.dictation.gui.main.DictationPanel;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Eamq
 */
public class AdvancedPanelFrame extends javax.swing.JFrame{

    private final JFileChooser myFC = new JFileChooser();
    private DictationPanel myDictPanel;

    /** Creates new form AdvancedPanelFrame */
    public AdvancedPanelFrame() {
        initComponents();
    }

	public AdvancedPanelFrame(DictationPanel dictPanel) {
        myDictPanel = dictPanel;       
        initComponents();
        advancedPanel1.setFileFilter(myFC);
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        advancedPanel1 = advancedPanel1 = new org.friendularity.dictation.gui.advanced.AdvancedPanel(myDictPanel.getImpl());
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemNew = new javax.swing.JMenuItem();
        itemOpen = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemQuit = new javax.swing.JMenuItem();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.friendularity.dictation.gui.main.DictationGrabberApp.class).getContext().getResourceMap(AdvancedPanelFrame.class);
        setTitle(resourceMap.getString("advancedPanelFrame.title")); // NOI18N
        setName("advancedPanelFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        advancedPanel1.setName("advancedPanel1"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        menuFile.setText(resourceMap.getString("menuFile.text")); // NOI18N
        menuFile.setName("menuFile"); // NOI18N

        itemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        itemNew.setMnemonic('N');
        itemNew.setText(resourceMap.getString("itemNew.text")); // NOI18N
        itemNew.setName("itemNew"); // NOI18N
        itemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNewActionPerformed(evt);
            }
        });
        menuFile.add(itemNew);

        itemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemOpen.setMnemonic('O');
        itemOpen.setText(resourceMap.getString("itemOpen.text")); // NOI18N
        itemOpen.setName("itemOpen"); // NOI18N
        itemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOpenActionPerformed(evt);
            }
        });
        menuFile.add(itemOpen);

        jSeparator2.setName("jSeparator2"); // NOI18N
        menuFile.add(jSeparator2);

        itemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        itemSave.setMnemonic('S');
        itemSave.setText(resourceMap.getString("itemSave.text")); // NOI18N
        itemSave.setName("itemSave"); // NOI18N
        itemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaveActionPerformed(evt);
            }
        });
        menuFile.add(itemSave);

        jSeparator1.setName("jSeparator1"); // NOI18N
        menuFile.add(jSeparator1);

        itemQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        itemQuit.setMnemonic('Q');
        itemQuit.setText(resourceMap.getString("itemQuit.text")); // NOI18N
        itemQuit.setName("itemQuit"); // NOI18N
        itemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQuitActionPerformed(evt);
            }
        });
        menuFile.add(itemQuit);

        jMenuBar1.add(menuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advancedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advancedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        myDictPanel.setAdvancedPanelOpen(false);
	}//GEN-LAST:event_formWindowClosing

    private void itemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQuitActionPerformed
        this.dispose();
        myDictPanel.setAdvancedPanelOpen(false);
    }//GEN-LAST:event_itemQuitActionPerformed

    private void itemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNewActionPerformed
        advancedPanel1.resetAll();
    }//GEN-LAST:event_itemNewActionPerformed

    private void itemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOpenActionPerformed
        try {
            advancedPanel1.loadFromFile(myFC);
        } catch (IOException ex) {
            System.out.println("Load operation failed.");
            Logger.getLogger(AdvancedPanelFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemOpenActionPerformed

    private void itemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaveActionPerformed
        try {
            advancedPanel1.saveToFile(myFC);
        } catch (IOException ex) {
            System.out.println("Save operation failed.");
            Logger.getLogger(AdvancedPanelFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemSaveActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvancedPanelFrame().setVisible(true);
            }
        });
    }

	public AdvancedPanel getAdvancedPanel(){
		return advancedPanel1;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.friendularity.dictation.gui.advanced.AdvancedPanel advancedPanel1;
    private javax.swing.JMenuItem itemNew;
    private javax.swing.JMenuItem itemOpen;
    private javax.swing.JMenuItem itemQuit;
    private javax.swing.JMenuItem itemSave;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuFile;
    // End of variables declaration//GEN-END:variables

}
