/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VolumeMonitorPanel.java
 *
 * Created on Jan 2, 2010, 12:47:05 AM
 */

package org.friendularity.dictation.gui.main;
import javax.swing.text.DefaultCaret;
/**
 *
 * @author Administrator
 */
public class VolumeMonitorPanel extends javax.swing.JPanel {

    /** Creates new form VolumeMonitorPanel */
    public VolumeMonitorPanel() {
        initComponents();
    }
   
	private java.util.Random myRand=new java.util.Random();
//	public void paintComponent(Graphics g) {
//		super.paintComponent(g);
////
////            try {
////                g.setColor(Color.red);
////                g.drawLine(0, 0, myRand.nextInt(this.getWidth()), myRand.nextInt(this.getHeight()));
////
////            } catch (Exception e) {
////
////				e.printStackTrace();
////            }
//	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStatusInfo = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(254, 98));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.friendularity.dictation.gui.main.DictationGrabberApp.class).getContext().getResourceMap(VolumeMonitorPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtStatusInfo.setColumns(20);
        txtStatusInfo.setEditable(false);
        txtStatusInfo.setFont(resourceMap.getFont("txtStatusInfo.font")); // NOI18N
        txtStatusInfo.setRows(5);
        txtStatusInfo.setName("txtStatusInfo"); // NOI18N
        jScrollPane1.setViewportView(txtStatusInfo);
        DefaultCaret caret = (DefaultCaret) txtStatusInfo.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtStatusInfo;
    // End of variables declaration//GEN-END:variables

    public void appendStatusInfo(String text) {
        txtStatusInfo.append(text);
    }

}
