package org.friendularity.bundle.demo.convo.response;

import org.osgi.framework.BundleContext;

/**
 *
 * @author Jason G. Pallack <jgpallack@gmail.com>
 */


public class ConvoResponseFrame extends javax.swing.JFrame {
    private DualQpidConnector myConnector;
    private Responder myResponder;
    
    /**
     * Creates new form ConvoResponseFrame
     */
    public ConvoResponseFrame() {
        initComponents();
        pack();
        myConnector = new DualQpidConnector();
        myResponder = new Responder(myConnector);
    }
    
    public void start(BundleContext context){
        myConnector.addListener(myResponder);
        dualQpidConnectionPanel1.setConnector(myConnector);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dualQpidConnectionPanel1 = new org.friendularity.bundle.demo.convo.response.DualQpidConnectionPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dualQpidConnectionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dualQpidConnectionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException ex) {
            org.slf4j.LoggerFactory.getLogger(ConvoResponseFrame.class).error(ex.getMessage(), ex);
        } catch(InstantiationException ex) {
            org.slf4j.LoggerFactory.getLogger(ConvoResponseFrame.class).error(ex.getMessage(), ex);
        } catch(IllegalAccessException ex) {
            org.slf4j.LoggerFactory.getLogger(ConvoResponseFrame.class).error(ex.getMessage(), ex);
        } catch(javax.swing.UnsupportedLookAndFeelException ex) {
            org.slf4j.LoggerFactory.getLogger(ConvoResponseFrame.class).error(ex.getMessage(), ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvoResponseFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.friendularity.bundle.demo.convo.response.DualQpidConnectionPanel dualQpidConnectionPanel1;
    // End of variables declaration//GEN-END:variables
}
