/*
 * FactMonitorPanel.java
 *
 * Created on July 30, 2009, 11:15 PM
 */

package org.friendularity.gui.fact;

import org.friendularity.gui.person.PersonTableModel.WrappingTextColumnRenderer;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author  Stu Baurmann
 */
public class FactMonitorPanel extends javax.swing.JPanel {

	private FactMonitorImpl		myImpl;
	private	FactTableModel		myTableModel;
    /** Creates new form FactMonitorPanel */
    public FactMonitorPanel() {
        initComponents();
		if (!java.beans.Beans.isDesignTime()) {
			myImpl = new FactMonitorImpl(this);
			myTableModel = new FactTableModel(myImpl);
			myFactTable.setModel(myTableModel);
			// myFactTable.setRowSorter(new TableRowSorter(myTableModel));
			initRenderers(myFactTable);
			resetColumnWidths();
		}
    }
	public void refreshContents() {
		// TODO add your handling code here:
		myTableModel.invalidateEverything();
		// resetColumnWidths();
		packRows(1, 50);
	}
	private void packRows(int margin, int maxRowHeight) {
		for (int r=0; r< myFactTable.getRowCount(); r++) {
			TableCellRenderer renderer = myFactTable.getCellRenderer(r, 4);
			Component comp = myFactTable.prepareRenderer(renderer, r, 4);
			comp.setSize(myFactTable.getColumnModel().getColumn(4).getWidth(), 999999);
			int rowHeight = comp.getPreferredSize().height + 2*margin;
			if (rowHeight > maxRowHeight) {
				rowHeight = maxRowHeight;
			}
			if (myFactTable.getRowHeight(r) != rowHeight) {
				myFactTable.setRowHeight(r, rowHeight);
			}
		}
	}
	public void initRenderers(JTable table) {
		TableColumnModel tcm = table.getColumnModel();
		TableColumn detailsCol = table.getColumnModel().getColumn(4);
		detailsCol.setCellRenderer(new WrappingTextColumnRenderer());
	}
	public void resetColumnWidths() {
		TableColumnModel colModel = myFactTable.getColumnModel();
		colModel.getColumn(0).setPreferredWidth(80);
		colModel.getColumn(1).setPreferredWidth(40);
		colModel.getColumn(2).setPreferredWidth(40);
		colModel.getColumn(3).setPreferredWidth(60);
		colModel.getColumn(4).setPreferredWidth(1200);
	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        factQueryToolsPanel = new javax.swing.JPanel();
        but_refresh = new javax.swing.JButton();
        txtFilter = new javax.swing.JTextField();
        btnClearFilter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        factResultPanel = new javax.swing.JPanel();
        myTableScrollPane = new javax.swing.JScrollPane();
        myFactTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        but_refresh.setText("refresh");
        but_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_refreshActionPerformed(evt);
            }
        });

        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFilterKeyPressed(evt);
            }
        });

        btnClearFilter.setText("Clear");
        btnClearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFilterActionPerformed(evt);
            }
        });

        jLabel1.setText("Type Filter");

        javax.swing.GroupLayout factQueryToolsPanelLayout = new javax.swing.GroupLayout(factQueryToolsPanel);
        factQueryToolsPanel.setLayout(factQueryToolsPanelLayout);
        factQueryToolsPanelLayout.setHorizontalGroup(
            factQueryToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, factQueryToolsPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(but_refresh)
                .addContainerGap())
        );
        factQueryToolsPanelLayout.setVerticalGroup(
            factQueryToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, factQueryToolsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(factQueryToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_refresh)
                    .addComponent(jLabel1)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearFilter))
                .addContainerGap())
        );

        add(factQueryToolsPanel, java.awt.BorderLayout.NORTH);

        factResultPanel.setLayout(new java.awt.BorderLayout());

        myFactTable.setAutoCreateRowSorter(true);
        myFactTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        myFactTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        myFactTable.setAutoscrolls(false);
        myFactTable.setRowHeight(32);
        myTableScrollPane.setViewportView(myFactTable);

        factResultPanel.add(myTableScrollPane, java.awt.BorderLayout.CENTER);

        add(factResultPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void but_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_refreshActionPerformed
	refreshContents();
}//GEN-LAST:event_but_refreshActionPerformed

private void txtFilterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        myTableModel.setFilters(txtFilter.getText());
    }
}//GEN-LAST:event_txtFilterKeyPressed

private void btnClearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFilterActionPerformed
    txtFilter.setText("");
    myTableModel.setFilters("");
}//GEN-LAST:event_btnClearFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearFilter;
    private javax.swing.JButton but_refresh;
    private javax.swing.JPanel factQueryToolsPanel;
    private javax.swing.JPanel factResultPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable myFactTable;
    private javax.swing.JScrollPane myTableScrollPane;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

}
