/**
 * Copyright 2008 Hanson Robotics Inc.
 * All Rights Reserved.
 */

package com.hansonrobotics.gui.servo;

import com.thoughtworks.xstream.converters.javabean.BeanProperty;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 * @author  humankind
 */
public class ServoTablePanel extends javax.swing.JPanel {

	private ServoMonitorImpl		myImpl;
    /** Creates new form ServoTablePanel */
    public ServoTablePanel() {
        initComponents();
		if (!java.beans.Beans.isDesignTime()) {
			myImpl = new ServoMonitorImpl();
			
			
			// myImpl.setControlBean(myThalamusControlBean);
			ObservableList servoChannelBeanList = myImpl.getServoChannelList();
			
			BindingGroup cbg = new BindingGroup();
			JTableBinding ctb = SwingBindings.createJTableBinding(
					AutoBinding.UpdateStrategy.READ, servoChannelBeanList, servo_joint_table);

			JTableBinding.ColumnBinding columnBinding = ctb.addColumnBinding(
					ELProperty.create("${logicalJointID}"));
			columnBinding.setColumnName("Joint ID");
			columnBinding.setColumnClass(Integer.class);

			columnBinding = ctb.addColumnBinding(
					ELProperty.create("${jointName}"));
			columnBinding.setColumnName("Joint Name");
			columnBinding.setColumnClass(String.class);
			
			columnBinding = ctb.addColumnBinding(
					ELProperty.create("${logicalJointValue}"));
			columnBinding.setColumnName("Lopsided C++ Value");
			columnBinding.setColumnClass(Double.class);

			columnBinding = ctb.addColumnBinding(
					ELProperty.create("${absRomPos}"));
			columnBinding.setColumnName("R.o.M. Position");
			columnBinding.setColumnClass(Double.class);
			
			cbg.addBinding(ctb);
			cbg.bind();		
			
			myImpl.setConfigBean(myServoMonitorConfigBean);
		}
    }
	public void doStartAll() {
		myServoMonitorConfigBean.setMonitoring(true);
	}
	public void disableControls() {
		button_refresh.setEnabled(false);
		toggle_updateContinuously.setEnabled(false);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        myServoMonitorConfigBean = new com.hansonrobotics.gui.servo.ServoMonitorConfigBean();
        panel_servoMonitoringControls = new javax.swing.JPanel();
        button_refresh = new javax.swing.JButton();
        toggle_updateContinuously = new javax.swing.JToggleButton();
        servo_joint_scroller = new javax.swing.JScrollPane();
        servo_joint_table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout(0, 20));

        panel_servoMonitoringControls.setBackground(new java.awt.Color(204, 51, 255));
        panel_servoMonitoringControls.setMaximumSize(new java.awt.Dimension(32767, 100));

        button_refresh.setText("refresh");
        button_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_refreshActionPerformed(evt);
            }
        });

        toggle_updateContinuously.setText("update continuously");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myServoMonitorConfigBean, org.jdesktop.beansbinding.ELProperty.create("${monitoring}"), toggle_updateContinuously, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout panel_servoMonitoringControlsLayout = new javax.swing.GroupLayout(panel_servoMonitoringControls);
        panel_servoMonitoringControls.setLayout(panel_servoMonitoringControlsLayout);
        panel_servoMonitoringControlsLayout.setHorizontalGroup(
            panel_servoMonitoringControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_servoMonitoringControlsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(button_refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(toggle_updateContinuously)
                .addGap(57, 57, 57))
        );
        panel_servoMonitoringControlsLayout.setVerticalGroup(
            panel_servoMonitoringControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_servoMonitoringControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_servoMonitoringControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_refresh)
                    .addComponent(toggle_updateContinuously))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panel_servoMonitoringControls, java.awt.BorderLayout.NORTH);

        servo_joint_scroller.setBackground(new java.awt.Color(51, 204, 0));
        servo_joint_scroller.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        servo_joint_scroller.setFont(new java.awt.Font("Tahoma", 0, 8));

        servo_joint_table.setAutoCreateRowSorter(true);
        servo_joint_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        servo_joint_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "joint name", "joint id", "joint pos", "servo id", "servo pos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        servo_joint_table.setFillsViewportHeight(true);
        servo_joint_table.setRowHeight(14);
        servo_joint_scroller.setViewportView(servo_joint_table);

        add(servo_joint_scroller, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

private void button_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_refreshActionPerformed
	myImpl.updateValues();
}//GEN-LAST:event_button_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_refresh;
    private com.hansonrobotics.gui.servo.ServoMonitorConfigBean myServoMonitorConfigBean;
    private javax.swing.JPanel panel_servoMonitoringControls;
    private javax.swing.JScrollPane servo_joint_scroller;
    private javax.swing.JTable servo_joint_table;
    private javax.swing.JToggleButton toggle_updateContinuously;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
