/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.friendularity.bundle.macro.behavior;

import java.util.Properties;

import org.cogchar.svc.behav.control.ActionCallbackMap;
import org.jflux.impl.services.rk.lifecycle.utils.SimpleLifecycle;
import org.jflux.impl.services.rk.osgi.lifecycle.OSGiComponent;
import org.osgi.framework.BundleContext;

/**
 *
 * @author eadsjr
 */
public class BehavoirMasterPanel extends javax.swing.JPanel {

    /**
     * Creates new form BehavoirMasterPanel
     */
    public BehavoirMasterPanel() {
        initComponents();
    }
    
    private boolean myInitFlag;
    
    public synchronized void init(BundleContext context, String behaviorID, String adminID) {
        if( myInitFlag ) { return; }
        
        String[] classnames = {ActionCallbackMap.class.getName(), ImageIconMap.class.getName()};
        //*
        behaviorIconTriggerPanel.init();
        Properties p = new Properties();        
        //TODO: fix this property, should refer to interface for ActionCallbackMap
        p.put(TriggerPanel.PROP_TRIGGER_PANEL_ID, behaviorID);
        p.put(ImageIconMap.PROP_IMAGE_ICON_MAP_ID, behaviorID);
        new OSGiComponent(context, 
                new SimpleLifecycle(behaviorIconTriggerPanel,classnames, p)).start();
        
        adminIconTriggerPanel.init();
        Properties p2 = new Properties();
        //TODO: fix this property, should refer to interface for ActionCallbackMap
        p2.put(TriggerPanel.PROP_TRIGGER_PANEL_ID, adminID);
        p2.put(ImageIconMap.PROP_IMAGE_ICON_MAP_ID, adminID);
        new OSGiComponent(context, 
                new SimpleLifecycle(adminIconTriggerPanel,classnames, p2)).start();
        //*/
        myInitFlag = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        behaviorMasterSplitPane = new javax.swing.JSplitPane();
        adminScrollPane = new javax.swing.JScrollPane();
        adminIconTriggerPanel = new IconTriggerPanel();
        behaviorScrollPane = new javax.swing.JScrollPane();
        behaviorIconTriggerPanel = new IconTriggerPanel();

        behaviorMasterSplitPane.setDividerLocation(240);

        javax.swing.GroupLayout adminIconTriggerPanelLayout = new javax.swing.GroupLayout(adminIconTriggerPanel);
        adminIconTriggerPanel.setLayout(adminIconTriggerPanelLayout);
        adminIconTriggerPanelLayout.setHorizontalGroup(
            adminIconTriggerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        adminIconTriggerPanelLayout.setVerticalGroup(
            adminIconTriggerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        adminScrollPane.setViewportView(adminIconTriggerPanel);

        behaviorMasterSplitPane.setRightComponent(adminScrollPane);

        javax.swing.GroupLayout behaviorIconTriggerPanelLayout = new javax.swing.GroupLayout(behaviorIconTriggerPanel);
        behaviorIconTriggerPanel.setLayout(behaviorIconTriggerPanelLayout);
        behaviorIconTriggerPanelLayout.setHorizontalGroup(
            behaviorIconTriggerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        behaviorIconTriggerPanelLayout.setVerticalGroup(
            behaviorIconTriggerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        behaviorScrollPane.setViewportView(behaviorIconTriggerPanel);

        behaviorMasterSplitPane.setLeftComponent(behaviorScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(behaviorMasterSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(behaviorMasterSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private IconTriggerPanel adminIconTriggerPanel;
    private javax.swing.JScrollPane adminScrollPane;
    private IconTriggerPanel behaviorIconTriggerPanel;
    private javax.swing.JSplitPane behaviorMasterSplitPane;
    private javax.swing.JScrollPane behaviorScrollPane;
    // End of variables declaration//GEN-END:variables
}
