/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.friendularity.bundle.macro.behavior;

import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;

import org.cogchar.svc.behav.control.ActionCallbackMap;
import org.jflux.api.core.Listener;

/**
 * Panel that adds and configures buttons during runtime.
 * 
 * Dynamically accepts ActionCallbacks and ImageIcons via interfaces. Callbacks
 * are used to make buttons. Icons that share their name with a callback are
 * associated with it to make an image button.
 * 
 * @author eadsjr
 */
public class IconTriggerPanel extends javax.swing.JPanel implements ActionCallbackMap, ImageIconMap {

    private Map<String,JButton> myButtonMap;
    private Map<String,ImageIcon> myIconMap;
    private boolean myInitFlag;

    /**
     * Creates new form IconTriggerPanel
     */
    public IconTriggerPanel() {
        initComponents();
        myButtonMap = new HashMap<String, JButton>();
        myIconMap = new HashMap<String, ImageIcon>();
        myInitFlag = false;
    }
    
    public void init(){
        if(myInitFlag){
            return;
        }
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        myInitFlag = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
                
    /**
     * If the action and icon for a button are both present, set the icon to the button
     * 
     * @param name The name of the button, as shared by the callback and icon
     */
    private void refreshButton( String name ) {
        if( myIconMap.containsKey(name) && myButtonMap.containsKey(name) )
        {
            ImageIcon icon = myIconMap.get(name);
            JButton button = myButtonMap.get(name);
            
            button.setIcon(icon);
            button.setText("");
            button.setVisible(true);
        }
        else if ( myButtonMap.containsKey(name) )
        {
            JButton button = myButtonMap.get(name);
            
            button.setIcon(null);
            button.setText(name);
            
            button.setVisible(true);
        }
        revalidate();
        repaint();
    }

    /**
     * Pushes a new button onto the Panel, with the specified listener.
     * 
     * @param actionCallbackName
     * @param actionCallbackListener 
     */
    @Override
    public void putActionCallback(String actionCallbackName, ActionListener actionCallbackListener){
        JButton b = new JButton(actionCallbackName);
        b.addActionListener(actionCallbackListener);
        myButtonMap.put(actionCallbackName, b);
        add(b);
        refreshButton(actionCallbackName);
    }

    /**
     * @param actionCallbackName
     * @return the listener for the given button
     */
    @Override
    public ActionListener getActionCallback(String actionCallbackName) {
        ActionListener result = null;
        JButton b = myButtonMap.get(actionCallbackName);
        if (b != null) { 
                ActionListener allAL[] = b.getActionListeners();
                if (allAL != null) {
                        if (allAL.length == 1) {
                                result = allAL[0];
                        }
                }
        }
        return result;
    }

    /**
     * Remove the specified button from the Panel.
     * 
     * @param actionCallbackName 
     */
    @Override
    public void removeActionCallback(String actionCallbackName) {
        JButton b = myButtonMap.remove(actionCallbackName);
        if(b != null){
            remove(b);
        }
    }
    
    /**
     * Stores an icon to be associated with a particular button.
     * 
     * @param imageIconName
     * @param imageIcon 
     */
    @Override
    public void putIconImage(String imageIconName, ImageIcon imageIcon) {
        myIconMap.put(imageIconName, imageIcon);
        refreshButton(imageIconName);
    }

    /** 
     * @param imageIconName
     * @return icon associated with the button of given name
     */
    @Override
    public ImageIcon getImageIcon(String imageIconName) {
        return myIconMap.get(imageIconName);
    }

    /**
     * Removes an imageIcon from a button and storage
     * 
     * @param imageIconName 
     */
    @Override
    public void removeImageIcon(String imageIconName) {
        myIconMap.remove(imageIconName);
        refreshButton(imageIconName);
    }
    public void addActionListener(Listener<String> listener){}
    
    public void removeActionListener(Listener<String> listener){}
    
    public void addActionRemoveListener(Listener<String> listener){}
    
    public void removeActionRemoveListener(Listener<String> listener){}
    
    public Set<String> getActionKeys()
    {
        return myButtonMap.keySet();
    }

}
