/**
 * Copyright 2008 Hanson Robotics Inc.
 * All Rights Reserved.
 */

package org.friendularity.gui.vision;

/**
 *
 * @author  humankind
 */
public class VisionChannelControlsPanel extends javax.swing.JPanel {

    /** Creates new form VisionChannelControlsPanel */
    public VisionChannelControlsPanel() {
        initComponents();
    }
    public Integer getHistDur() {
		return (Integer) spin_histDur.getValue();
	}
    public Integer getSegDurThresh() {
		return (Integer) spin_segDurThresh.getValue();
	}
	public Integer getDeltaAmpThresh() {
		return (Integer) spin_deltaAmpThresh.getValue();
	}
	public Integer getResultAmpThresh() {
		return (Integer) spin_resultAmpThresh.getValue();
	}

    public VisionMonitorChannelBean getChannelConfigBean() {
        return myChannelBean;
    }
	public void disableControls() {
		channelSpinner.setEnabled(false);
		checkboxInvertVideo.setEnabled(false);
		toggleDetectFaces.setEnabled(false);
		toggleDetectMotion.setEnabled(false);
		toggleRecogFaces.setEnabled(false);
		toggleShowRawFrames.setEnabled(false);
		toggleTrackFaces.setEnabled(false);
	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        myChannelBean = new org.friendularity.gui.vision.VisionMonitorChannelBean();
        toggleDetectFaces = new javax.swing.JToggleButton();
        toggleTrackFaces = new javax.swing.JToggleButton();
        channelSelLabel = new javax.swing.JLabel();
        channelSpinner = new javax.swing.JSpinner();
        toggleShowRawFrames = new javax.swing.JToggleButton();
        toggleDetectMotion = new javax.swing.JToggleButton();
        toggleRecogFaces = new javax.swing.JToggleButton();
        checkboxInvertVideo = new javax.swing.JCheckBox();
        spin_histDur = new javax.swing.JSpinner();
        spin_deltaAmpThresh = new javax.swing.JSpinner();
        spin_segDurThresh = new javax.swing.JSpinner();
        spin_resultAmpThresh = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        toggleDetectFaces.setText("detect faces");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myChannelBean, org.jdesktop.beansbinding.ELProperty.create("${detectingFaces}"), toggleDetectFaces, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        toggleDetectFaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleDetectFacesActionPerformed(evt);
            }
        });

        toggleTrackFaces.setText("track faces");
        toggleTrackFaces.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myChannelBean, org.jdesktop.beansbinding.ELProperty.create("${trackingFaces}"), toggleTrackFaces, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        toggleTrackFaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleTrackFacesActionPerformed(evt);
            }
        });

        channelSelLabel.setText("channel:");

        channelSpinner.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myChannelBean, org.jdesktop.beansbinding.ELProperty.create("${channelNumber}"), channelSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        toggleShowRawFrames.setText("show video");
        toggleShowRawFrames.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myChannelBean, org.jdesktop.beansbinding.ELProperty.create("${grabbingFrames}"), toggleShowRawFrames, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        toggleShowRawFrames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleShowRawFramesActionPerformed(evt);
            }
        });

        toggleDetectMotion.setText("detect motion");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myChannelBean, org.jdesktop.beansbinding.ELProperty.create("${detectingMotion}"), toggleDetectMotion, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        toggleDetectMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleDetectMotionActionPerformed(evt);
            }
        });

        toggleRecogFaces.setText("recog faces");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myChannelBean, org.jdesktop.beansbinding.ELProperty.create("${recognizingFaces}"), toggleRecogFaces, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        toggleRecogFaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleRecogFacesActionPerformed(evt);
            }
        });

        checkboxInvertVideo.setText("Flip Vertical");
        checkboxInvertVideo.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, myChannelBean, org.jdesktop.beansbinding.ELProperty.create("${flippingVideoVertical}"), checkboxInvertVideo, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        checkboxInvertVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxInvertVideoActionPerformed(evt);
            }
        });

        spin_histDur.setModel(new javax.swing.SpinnerNumberModel(6, 1, 99, 1));

        spin_deltaAmpThresh.setModel(new javax.swing.SpinnerNumberModel(15, 1, 255, 1));

        spin_segDurThresh.setModel(new javax.swing.SpinnerNumberModel(3, 1, 99, 1));

        spin_resultAmpThresh.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));

        jLabel1.setText("histDur");

        jLabel2.setText("dAmpT");

        jLabel3.setText("segDurT");

        jLabel4.setText("rAmpT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(channelSelLabel)
                        .addGap(2, 2, 2)
                        .addComponent(channelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(checkboxInvertVideo))
                            .addComponent(toggleShowRawFrames, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(toggleDetectMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toggleDetectFaces, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toggleTrackFaces, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toggleRecogFaces, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spin_histDur, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spin_resultAmpThresh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(spin_segDurThresh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(spin_deltaAmpThresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(channelSelLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(channelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxInvertVideo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleShowRawFrames, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleDetectMotion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleDetectFaces, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleTrackFaces, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleRecogFaces, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spin_histDur, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spin_segDurThresh, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spin_deltaAmpThresh, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spin_resultAmpThresh, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

private void toggleDetectFacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleDetectFacesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_toggleDetectFacesActionPerformed

private void toggleTrackFacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleTrackFacesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_toggleTrackFacesActionPerformed

private void toggleShowRawFramesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleShowRawFramesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_toggleShowRawFramesActionPerformed

private void toggleDetectMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleDetectMotionActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_toggleDetectMotionActionPerformed

private void toggleRecogFacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleRecogFacesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_toggleRecogFacesActionPerformed

private void checkboxInvertVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxInvertVideoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_checkboxInvertVideoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel channelSelLabel;
    private javax.swing.JSpinner channelSpinner;
    private javax.swing.JCheckBox checkboxInvertVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.friendularity.gui.vision.VisionMonitorChannelBean myChannelBean;
    private javax.swing.JSpinner spin_deltaAmpThresh;
    private javax.swing.JSpinner spin_histDur;
    private javax.swing.JSpinner spin_resultAmpThresh;
    private javax.swing.JSpinner spin_segDurThresh;
    private javax.swing.JToggleButton toggleDetectFaces;
    private javax.swing.JToggleButton toggleDetectMotion;
    private javax.swing.JToggleButton toggleRecogFaces;
    private javax.swing.JToggleButton toggleShowRawFrames;
    private javax.swing.JToggleButton toggleTrackFaces;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
